version: '3'

networks:
  file-manager-service:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: file-manager-service-nginx
    ports:
      - '8050:80'
    volumes:
      - ./laravel:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fpm
    networks:
      - file-manager-service
    restart: always

  fpm:
    build:
      context: .
      dockerfile: fpm/Dockerfile
    container_name: file-manager-service-fpm
    volumes:
      - ./laravel:/var/www/html
      - ./fpm/upload.ini:/usr/local/etc/php/conf.d/upload.ini
    networks:
      - file-manager-service
    restart: always

  mariadb:
    image: mariadb:latest
    container_name: file-manager-service-mariadb
    tty: true
    ports:
      - '8051:3306'
    environment:
      MYSQL_DATABASE: file-manager-service
      MYSQL_USER: lfm
      MYSQL_PASSWORD: lfm
      MYSQL_ROOT_PASSWORD: lfm
    volumes:
      - 'file-manager-service-mariadb:/var/lib/mysql'
      - './mariadb:/etc/mysql/conf.d'
    networks:
      - file-manager-service
    restart: always

volumes:
  file-manager-service-mariadb: null
